include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/gen_l10n/**
    - build/**
    - android/**

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    unawaited_futures: true
